### ISSUE TITLE
Issue on handler of CS02e response

### ISSUE THREAD

**Issue by nunocaires** [HenryGiraldo/gbcs-parser-js#9]
Function parseUpdateDeviceCertificateResponse is defined twice and incorrectly used by CS02e.

To fix the issue:

* Refactor **parseUpdateDeviceCertificateResponse** to **parseProviderDeviceCertificateResponse**
* Change CS02e response handler to use the "new" refactored **parseProviderDeviceCertificateResponse**

![gbcs-parser-fix](https://user-images.githubusercontent.com/20713950/69329688-d5f97080-0c51-11ea-80e3-5d4a258bfacc.png)

**Comment by HenryGiraldo** [comment]
Changes applied in 0cc2cbb609baad06a668b6d415d7ce35846f9ab3.

Thanks Nuno, next time if possible use use pull request please.

**Comment by nunocaires** [comment]
Hey Henry,

I never used github before still need to learn a bit. I did try to create
a PR but it was denied due to lack of permissions. I also tried to push a
feature branch in order to do a merge request but again without success due
to permissions.
What is the correct way to do it? Your repo permissions allows for that?

Cheers,
Nuno

**Comment by HenryGiraldo** [comment]
Hi Nuno, I guess you tried a push directly to the repository.

The easiest way to do a pull request is:
- Fork the repository.
- Do the commit in your own repository.
- From your repository ask for a pull request.

Cheers!
